### ISSUE TITLE
Create a mock server derive from milvus grpc service class

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus-sdk-cpp#14]
A server to mock milvus server. 
- a server class derive from milvus grpc service class, a localhost grpc server listen to a port
- a class to implement milvus service interface, used by the server class with composite mode
- can specify customize response for each api

**Comment by matrixji** [comment]
- [x] a server class derive from milvus grpc service class, a localhost grpc server listen to a port
- [x] a class to implement milvus service interface, used by the server class with composite mode
- [ ] can specify customize response for each API

Related PR: #38 should cover 1 & 2, for 2 actually using a strict gmock server instance.

For the 3, after I add all MOCK instances, and create some common code to simplify build response, I will mark it as DONE.
