### ISSUE TITLE
Failed to search: no Available QueryNode result

### ISSUE THREAD

**Issue by jackweiwang** [milvus-io/milvus-sdk-cpp#158]
System version : CentOS Linux release 7.7.1908 (Core)
Milvus server version: v2.0.0
SDK client version:master
ErrorInfo:
`Failed to search: no Available QueryNode result, filter reason [UnexpectedError] Assert "adapter->CheckSearch(conf, index_type, field_indexing->indexing_->index_mode())" at /go/src/github.com/milvus-io/milvus/internal/core/src/query/SearchOnSealed.cpp:91
 => [SearchOnSealed]Search params check failed
: id 431494463105583403`

[main.log](https://github.com/milvus-io/milvus-sdk-cpp/files/8158269/main.log)

**Comment by matrixji** [comment]
@jackweiwang  more information requested. Could you provide how you create index (index_type, metric_type, nlist, etc)?

**Comment by jackweiwang** [comment]
_METRIC_TYPE = 'L2'
_INDEX_TYPE = 'IVF_FLAT'
_NLIST = 1024
_NPROBE = 16

index_param = {
    "index_type": _INDEX_TYPE, 
    "params": {"nlist": _NLIST},
    "metric_type": _METRIC_TYPE} 
collection.create_index(filed_name, index_param)

**Comment by matrixji** [comment]
RC:
Currently, all extra search params are using <string:string> pair in JSON. need to support <string:number> pair for it.

**Comment by yhmo** [comment]
@jackweiwang 

The source code in the main.log searches for an empty collection. So I add some lines to insert entities into the collection.
And do search with gruantee_timestamp=strong. Then it works fine.

```
#include <iostream>
#include <random>
#include <string>

#include "milvus/MilvusClient.h"
#include "milvus/types/CollectionSchema.h"

void
CheckStatus(std::string&& prefix, const milvus::Status& status) {
    if (!status.IsOk()) {
        std::cout << prefix << " " << status.Message() << std::endl;
        exit(1);
    }
}

int
main(int argc, char* argv[]) {
    printf("Example start...\n");

    auto client = milvus::MilvusClient::Create();

    milvus::ConnectParam connect_param{"localhost", 19530};
    auto status = client->Connect(connect_param);
    CheckStatus("Failed to connect milvus server:", status);
    std::cout << "Connect to milvus server." << std::endl;

    // drop the collection if it exists

    const std::string collection_name = "aaa";
    const std::string field_id_name = "id";
    const std::string field_embedding_name = "face";

    const uint32_t dimension = 32;

    milvus::CollectionSchema collection_schema(collection_name);
    collection_schema.AddField({field_id_name, milvus::DataType::INT64, "user id", true, false});
    collection_schema.AddField(
        milvus::FieldSchema(field_embedding_name, milvus::DataType::FLOAT_VECTOR, "user embedding")
            .WithDimension(dimension));
    client->DropCollection(collection_name);
    client->CreateCollection(collection_schema);

    // tell server prepare to load collection
    status = client->LoadCollection(collection_name);
    CheckStatus("Failed to load collection:", status);

    const int64_t row_count = 1000;
    std::vector<int64_t> insert_ids;
    std::vector<std::vector<float>> insert_vectors;
    std::default_random_engine ran(time(nullptr));
    std::uniform_int_distribution<int8_t> int_gen(1, 100);
    std::uniform_real_distribution<float> float_gen(0.0, 1.0);
    for (auto i = 0; i < row_count; ++i) {
        insert_ids.push_back(i);
        std::vector<float> vector(dimension);

        for (auto i = 0; i < dimension; ++i) {
            vector[i] = float_gen(ran);
        }
        insert_vectors.emplace_back(vector);
    }

    std::vector<milvus::FieldDataPtr> fields_data{
        std::make_shared<milvus::Int64FieldData>(field_id_name, insert_ids),
        std::make_shared<milvus::FloatVecFieldData>(field_embedding_name, insert_vectors)};
    milvus::DmlResults dml_results;
    status = client->Insert(collection_name, "", fields_data, dml_results);

    // do search
    milvus::SearchArguments arguments{};
    arguments.SetCollectionName(collection_name);
    arguments.SetTopK(10);
    arguments.SetMetricType(milvus::MetricType::L2);

    arguments.AddExtraParams("nprobe", "10");
    // set to strong guarantee so that the search is executed after the inserted data is persisted
    arguments.SetGuaranteeTimestamp(milvus::GuaranteeStrongTs());

    std::vector<float> q_vector(dimension);
    for (auto i = 0; i < dimension; ++i) {
        q_vector[i] = float_gen(ran);
        std::cout << q_vector[i] << std::endl;
    }

    std::cout << field_embedding_name << " " << q_vector.size() << std::endl;

    arguments.AddTargetVector(field_embedding_name, q_vector);

    milvus::SearchResults search_results{};
    status = client->Search(arguments, search_results);
    CheckStatus("Failed to search:", status);
    std::cout << "Successfully search." << std::endl;

    for (auto& result : search_results.Results()) {
        auto& ids = result.Ids().IntIDArray();
        auto& distances = result.Scores();
        if (ids.size() != distances.size()) {
            std::cout << "Illegal result!" << std::endl;
            continue;
        }

        for (size_t i = 0; i < ids.size(); ++i) {
            std::cout << "ID: " << ids[i] << "\tDistance: " << distances[i] << std::endl;
        }
    }

    return 0;
}
```

We didn't check insert data in the Insert() interface, if the primary field "id"  auto_id=true, and you provide an id array for the Insert(), it may caused unexpected error in server side.

**Comment by matrixji** [comment]
I guess @jackweiwang already inserts data by other SDK (Java's or pymilvus) before running his search code.

**Comment by jackweiwang** [comment]
@yhmo @matrixji Yes, i already inserts data by pymilvus sdk.

**Comment by matrixji** [comment]
> @yhmo @matrixji Yes, i already inserts data by pymilvus sdk, and i have many vectors of different dimensions inserted into different collection.

If possible you could help to run your code with the master branch from `https://github.com/matrixji/milvus-sdk-cpp`, the PR #162 is already ongoing, hope this could fix the problem.

**Comment by jackweiwang** [comment]
> > @yhmo @matrixji Yes, i already inserts data by pymilvus sdk, and i have many vectors of different dimensions inserted into different collection.
> 
> If possible you could help to run your code with the master branch from `https://github.com/matrixji/milvus-sdk-cpp`, the PR #162 is already ongoing, hope this could fix the problem.

[root@bb8993a653e1 ~/milvus_matrixji/milvus-sdk-cpp/build/examples/simple]# ./sdk_simple 
Example start...
Connect to milvus server.
embedding 32
Failed to search: no Available QueryNode result, filter reason [UnexpectedError] Assert "adapter->CheckSearch(conf, index_type, field_indexing->indexing_->index_mode())" at /go/src/github.com/milvus-io/milvus/internal/core/src/query/SearchOnSealed.cpp:91
 => [SearchOnSealed]Search params check failed
: id 431494463105583731
[root@bb8993a653e1 ~/milvus_matrixji/milvus-sdk-cpp/build/examples/simple]# git branch -vv
* master 72359b0 [origin/master] Fix SearchArguments/CreateIndex

**Comment by matrixji** [comment]
> Available QueryNode result, filter

Sorry for missing one thing, you may need to change `arguments.AddExtraParams("nprobe", "10");` -> `arguments.AddExtraParams("nprobe", 10);`. I'm not sure if we later need to support some interface like `Nprobe(size_t nprobe);`

**Comment by yhmo** [comment]
@matrixji 
I think it is valuable to add interfaces to help users to set parameters correctly. We can check these parameters by index type, give errors as earlier as we can. For example, if a user creates IVF_PQ index by the CreateIndex(), we can check the parameters at the pre-stage, require him to input "nlist", "m", "nbits".

Another problem is the IndexDesc has no method to specify index type. The rpc proto interface requires a "index_type":
**message CreateIndexRequest {
  // Support keys: index_type,metric_type, params. Different index_type may has different params.
  repeated common.KeyValuePair extra_params = 5; 
}**
I guess the CreateIndex() can't work currently.

**Comment by matrixji** [comment]
> @matrixji I think it is valuable to add interfaces to help users to set parameters correctly. We can check these parameters by index type, give errors as earlier as we can. For example, if a user creates IVF_PQ index by the CreateIndex(), we can check the parameters at the pre-stage, require him to input "nlist", "m", "nbits".
> 
> Another problem is the IndexDesc has no method to specify index type. The rpc proto interface requires a "index_type":
> 
> ```
> message CreateIndexRequest {
>   // Support keys: index_type,metric_type, params. Different index_type may has different params.
>   repeated common.KeyValuePair extra_params = 5; 
> }
> ```
> 
> I guess the CreateIndex() can't work currently.

Agreed.
Currently, we need to use the below code to CreateIndex in CPP's SDK. It's ugly and not easy to document.

https://github.com/milvus-io/milvus-sdk-cpp/blob/b829b4726d9fd428e7ce2b8bb2eaa99faf062085/test/st/TestSearch.cpp#L147-L153

 Some there should be more refinements for CreateIndex and Search interface.
