### ISSUE TITLE
Proposal discussion: a detail class graph for the sdk

### ISSUE THREAD

**Issue by yhmo** [milvus-io/milvus-sdk-cpp#16]
- a proposal to define the client implementation classes
- discuss proposal in this issue
- put the proposal into the [MEP page](https://wiki.lfaidata.foundation/pages/viewpage.action?pageId=52265005) once the proposal is agreed by all collaborators

**Comment by matrixji** [comment]
Do we possibly borrow the interface design from [milvus-sdk-java](https://github.com/milvus-io/milvus-sdk-java)?

**Comment by yhmo** [comment]
> Do we possibly borrow the interface design from [milvus-sdk-java](https://github.com/milvus-io/milvus-sdk-java)?

I am also thinking about this question. @ArkaprabhaChakraborty mentioned we can create a similar orm similar to the python sdk. I think the sdk can be designed as two levels:
- the orm classes: ConnectionInstance/Collection/Partition/Index/Schema/Parameters, and maybe ConnectionPool
- the client implementation: a class to maintain grpc channel, a class to transfer parameters to rpc interface and with some logic like the pymilvus/client/grpc_handler.py

**Comment by yhmo** [comment]
Basically, the client implementation can do all things. Orm classes can be an enhancement for usability.

**Comment by ArkaprabhaChakraborty** [comment]
I'll add some initial orm classes. Their tests and their respective client implementations. I guess that should do. And then I can make further issues which I and @matrixji can divide between ourselves? Also I'll change the MEP. What do you say? My approach might be wrong so please do correct me if so.

**Comment by yhmo** [comment]
@ArkaprabhaChakraborty 
Please attach your proposal here, we can discuss together. 
Just like the "collection alias" feature: https://github.com/milvus-io/milvus/issues/4812, firstly we have a raw proposal, we discuss it in the issue page, finally we put the final design into the MEP page: https://wiki.lfaidata.foundation/display/MIL/MEP+10+--+Support+Collection+Alias

**Comment by ArkaprabhaChakraborty** [comment]
**Class Graph Proposal**

So I was proposing the following structure:

```
------client
         |
         ------- stub
                  |
                  ------- Milvus
         |
         ------- prepare
                  |
                  ------ Prepare
         |
         ------- types
                  |
                  ------  Status
                  |
                  ------- DataType
                  |
                  ------- RangeType
                  |          
                  ------- IndexType
         |
         ------- exceptions
                  |
                  -------  ParamError
                  |
                  ------- ConnectError
                  |
                  ------- NotConnectError
                  |          
                  ------- RepeatingConnectError,
                  |
                  ------- VersionError,
                  | 
                  ------- BaseException 
    
```

**Comment by matrixji** [comment]
> **Class Graph Proposal**
> 
> So I was proposing the following structure:
> 
> ```
> ------client
>          |
>          ------- stub
>                   |
>                   ------- Milvus
>          |
>          ------- prepare
>                   |
>                   ------ Prepare
>          |
>          ------- types
>                   |
>                   ------  Status
>                   |
>                   ------- DataType
>                   |
>                   ------- RangeType
>                   |          
>                   ------- IndexType
>          |
>          ------- exceptions
>                   |
>                   -------  ParamError
>                   |
>                   ------- ConnectError
>                   |
>                   ------- NotConnectError
>                   |          
>                   ------- RepeatingConnectError,
>                   |
>                   ------- VersionError,
>                   | 
>                   ------- BaseException 
>     
> ```

IMO, In c++, generally, we release SDK with headers and library, this is a lit bit different with java/python.
I think we could organize our code structure like below(put public header in `include`, source and internal header in `impl` ):
```plain
include\
+-- MilvusClient.h
+-- exceptions\
    +-- BaseException.h
    +-- ParamError.h
    +-- ...
+-- types\
    +-- Status.h
    +-- ...
impl\
    +-- MilvusClientImpl.h
    +-- MilvusClientImpl.cpp
+-- exceptions\
    +-- BaseException.cpp
    +-- ParamError.cpp
    +-- ...
+-- types\
    +-- Status.cpp
    +-- ...
+-- prepare\
    +-- ...
...
```

**Comment by yhmo** [comment]
As @matrixji mentioned, we need to provide headers of static link library, all exported headers should be put into the "include" folder. Internal headers and implementation files(cxx/cpp) should be put into "impl" folder. This is a common way to develop a C++ library.

There are some other files generated by gRPC, not sure where to put these files. In my opinion, these files are generated by third-party, no need to put them into the "impl" folder. @ArkaprabhaChakraborty  Is the "stub" folder for these files?

My another suggestion is the "prepare" folder, the pymilvus use this folder for parameters preparation classes. Personally I think the word "prepare" is meaningless(prepare what?). In Java SDK, we use "param" folder for parameters preparation/validation classes, I think the word "param" is more clear.

So, combine your code structures:
```
---- include
         |---- MilvusClient.h
         |---- param
                    |---- CreateCollectionParam.h
         |---- exceptions
                    |---- BaseException.h
                    |---- ParamError.h
         |---- types
                    |---- Status.h
---- impl
         |---- MilvusClientImpl.h
         |---- MilvusClientImpl.cpp
         |---- param
                    |---- CreateCollectionParam.cpp
         |---- exceptions
                    |---- BaseException.cpp
                    |---- ParamError.cpp
         |---- types
                    |---- Status.cpp
---- stub
         |---- milvus.pb.h
         |---- milvus.pb.cc
         |---- common.pb.h
         |---- common.pb.cc
         |---- schema.pb.h
         |---- schema.pbcc
```

**Comment by yhmo** [comment]
For example, to declare CreateCollection() interface:

|---- include
        |---- MilvusClient.h
        |---- param
                  |---- BaseParam.h
                  |---- CreateCollectionParam.h
        |---- types
                  |---- FieldSchema.h
                  |---- CollectionSchema.h


The declarations:

src/include/MilvusClient.h
```
#pragma once
#include "types/Status.h"


/**
 *  @brief namespace milvus
 */
namespace milvus {

/**
 * @brief milvus client abstract class
 */
class MilvusClient {
 public:
    virtual void
    Dummy() = 0;

    virtual Status CreateCollection(const CreateCollectionParam& param) = 0;
};

}  // namespace milvus
```
src/include/param/BaseParam.h
```
#pragma once
#include "types/Status.h"

namespace milvus {

class BaseParam {
 public:
    virtual Status Verify() = 0;
};

}
```

src/include/param/CreateCollectionParam.h
```
#pragma once

#include "BaseParam.h"
#include "type/CollectionSchema.h"

namespace milvus {

class CreateCollectionParam : public BaseParam {
 public:
    CreateCollectionParam(CollectionSchema& schema);
    Status Verify();

 private:
    CollectionSchema schema;
};

}

```

src/include/param/CreateCollectionParam.h
```
#pragma once

#include <string>
#include <vector>

#include "FieldSchema.h"

namespace milvus {

class CollectionSchema {
 public:
    
 private:
    /**
     * @brief Name of this collection, cannot be empty
     */
    std::string name;

    /** 
     * @brief Description of this collection, can be empty 
     */
    std::string description;

    /** 
     * @brief Set shards number, the number must be larger than zero, default value is 2. 
     */
    int32_t shard_num = 2;
};

}
```

src/include/types/FieldSchema.h
```
#pragma once

#include <string>
#include <map>

#include "DataType.h"

namespace milvus {

class FieldSchema {
 public:
    
    
 private:
    /**
     * @brief Name of this field, cannot be empty
     */
    std::string name;

    /** 
     * @brief Description of this field, can be empty 
     */
    std::string description;

    /**
     * @brief Field data tpye 
     * 
     */
    DataType data_type;

    /**
     * @brief Specify the field to be primary key
     * 
     * Each collection only has one primary key.
     * Currently only int64 type field can be primary key .
     */
    bool is_primary_key = false;

    /**
     * @brief Let server automatically generate id for this field
     * 
     * If ths flag is true, server will generate id when data is inserted.
     * Else the client must provide id for each entity when insert data.
     * 
     */
    bool auto_id = false;

    /**
     * @brief Extra key-value pair setting for this field
     * 
     * Currently vector field need to input "dim":"x" to specify dimension.
     * 
     */
    std::map<std::string, std::string> type_params;
};

}
```

**Comment by ArkaprabhaChakraborty** [comment]
> As @matrixji mentioned, we need to provide headers of static link library, all exported headers should be put into the "include" folder. Internal headers and implementation files(cxx/cpp) should be put into "impl" folder. This is a common way to develop a C++ library.

Yes agreed. I have worked in different projects which use this structure. And I guess this will be better for us too.

> There are some other files generated by gRPC, not sure where to put these files. In my opinion, these files are generated by third-party, no need to put them into the "impl" folder. @ArkaprabhaChakraborty Is the "stub" folder for these files?

Yes the stub should have these files. I mean in the python-sdk, these files are in stub I guess so ..  

> My another suggestion is the "prepare" folder, the pymilvus use this folder for parameters preparation classes. Personally I think the word "prepare" is meaningless(prepare what?). In Java SDK, we use "param" folder for parameters preparation/validation classes, I think the word "param" is more clear.

Do we need this? If so then we can create a params/param folder.

> So, combine your code structures:
> 
> ```
> ---- src
>     |---- include
>         |---- MilvusClient.h
>         |---- param
>                   |---- CreateCollectionParam.h
>         |---- exceptions
>                   |---- BaseException.h
>                   |---- ParamError.h
>         |---- types
>                   |---- Status.h
>     |---- impl
>         |---- MilvusClientImpl.h
>         |---- MilvusClientImpl.cpp
>         |---- param
>                   |---- CreateCollectionParam.cpp
>         |---- exceptions
>                   |---- BaseException.cpp
>                   |---- ParamError.cpp
>         |---- types
>                   |---- Status.cpp
>     |---- stub
>         |---- milvus.pb.h
>         |---- milvus.pb.cc
>         |---- common.pb.h
>         |---- common.pb.cc
>         |---- schema.pb.h
>         |---- schema.pbcc
> ```

Yes I had a sort of design like this in my mind, but I couldn't define it well. Thanks for the help

**Comment by yhmo** [comment]
I just create a pr for first api CreateCollection(), and an example program to use the sdk as a static link library. Just ignore the "param" folder, I think it is belong to ORM.

**Comment by yhmo** [comment]
@matrixji @ArkaprabhaChakraborty 
Please take a look the #26, this pr implement the CreateCollection() api. Now you can run the example can create a collection in milvus.

So the first level of client implementation is mainly the two classes: MilvusConnection and MilvusClientImpl, The MilvusConnection maintain a connection between client and milvus server. The MilvusClientImpl convert users parameters into grpc format and pass to MilvusConnection.

After this pr merged, we can start tasks parallelly. We can create a task for each api(some simple api can be merged into one task).

When the first level is done, we all be familiar with the client behavior, then we can consider to design the orm classes and implement the second level functions.

**Comment by matrixji** [comment]
Shall we close this issue? Seems we've implemented all low-level interfaces for MilvusClient
@yhmo @ArkaprabhaChakraborty

**Comment by ArkaprabhaChakraborty** [comment]
I guess so
