### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by suiguoxin** [milvus-io/milvus-sdk-cpp#172]
`mkdir build && cd build && cmake ../ && make` command failed with the following error:
```
[ 95%] Built target protoc
make[2]: *** No rule to make target '../src/milvus-proto/proto/schema.proto', needed by '../src/proto-gen/schema.pb.cc'.  Stop.
CMakeFiles/Makefile2:3136: recipe for target 'src/CMakeFiles/milvus_sdk_shared.dir/all' failed
make[1]: *** [src/CMakeFiles/milvus_sdk_shared.dir/all] Error 2
Makefile:165: recipe for target 'all' failed
make: *** [all] Error 2

```

BTW, is this sdk ready for test? I'd like to run the example here: https://github.com/milvus-io/milvus-sdk-cpp/blob/master/examples/simple/main.cpp,

**Comment by matrixji** [comment]
Recently the proto files move to submodule, so we need to update submodule before compiling.
```
git submodule update --init
```

We also need to update the guide/README for this change.

**Comment by suiguoxin** [comment]
> 

Thanks for the reply, it works. Do you have a release plan for the C++ SDK?

**Comment by matrixji** [comment]
I think it is planned for the first release with Milvus 2.1. And the code on the master branch is almost ready for use.

Ref: https://wiki.lfaidata.foundation/pages/viewpage.action?pageId=52267944
