### ISSUE TITLE
Error: Assert "field_indexing->metric_type_ == search_info.metric_type_"

### ISSUE THREAD

**Issue by Xiejiadong** [milvus-io/milvus-sdk-cpp#173]
I met an error when I try to use the change the code of the sample, the error is "
Failed to search: no Available QueryNode result, filter reason [UnexpectedError] Assert "field_indexing->metric_type_ == search_info.metric_type_" at /go/src/github.com/milvus-io/milvus/internal/core/src/query/SearchOnSealed.cpp:80".

Is it means the type of the targetvector of the search is not the same as the data?

**Comment by xiaofan-luan** [comment]
when you build index, you should use same metric_type as search do~

**Comment by Xiejiadong** [comment]
In fact, we use py to save and build the index, then we try to use C++ to search, and use `vector<float>`.
I wonder how to solve this error. Thanks~

**Comment by matrixji** [comment]
> In fact, we use py to save and build the index, then we try to use C++ to search, and use `vector<float>`. I wonder how to solve this error. Thanks~

You need to set the metric type for SearchArguments, which is not included in the sample code from `milvus-sdk-cpp` so far.
Maybe the below code in the test is an example of how to set metric-type 

https://github.com/milvus-io/milvus-sdk-cpp/blob/ac4812d015ce363f21281068a77efea8fc94cd9d/test/st/TestSearch.cpp#L157
