### ISSUE TITLE
Discussion: Support multiple platform such as macOS, windows

### ISSUE THREAD

**Issue by matrixji** [milvus-io/milvus-sdk-cpp#18]
Recently, I'm trying to set up a development environment for `milvus-sdk-cpp` under my M1-based macbook. It failed while compiling grpc. Currently, I'm back working with Linux.

Maybe this is a further topic we could handle after the initial version was done under Linux. IMO we could have some discussions right now.
**Do we need to support other platforms for the cpp SDK? And if so, what is the detailed solution ...**

AIK, grpc/Zlib currently are supported for windows/macOS officially.

**Comment by yhmo** [comment]
Milvus server can only run on linux OS. But SDK should be no limited by OS. Ideally, user ought to can use sdk in mainstream operation system including Mac, Windows, Linux.
