### ISSUE TITLE
How to set Consistency level in milvus ?

### ISSUE THREAD

**Issue by kingkong135** [milvus-io/milvus-sdk-cpp#180]
In python sdk i see there is a place to set Consistency level at collection like:

```python
hello_milvus = Collection("hello_milvus", schema, consistency_level="Strong")
```

But in cpp i don't find it. How to be like I need performance while searching.

**Comment by matrixji** [comment]
As this consistency_level is finally used for the Search interface, you could try using SetGuaranteeTimestamp to set different guarantee timestamps for the search arguments.


like below code for your requirement(performance while searching).
```cpp
milvus::SearchArguments arguments{};
arguments.SetCollectionName("foo");
arguments.AddPartitionName("bar");
arguments.SetTopK(10);
arguments.AddOutputField("test");
arguments.SetExpression(field_age_name + " > 40");
// GuaranteeEventuallyTs or GuaranteeStrongTs or see 
arguments.SetGuaranteeTimestamp(milvus::GuaranteeEventuallyTs());
```

Currently, for my understanding, the `consistency_level` is a client behavior, so we could use GuaranteeTimestamp to do this also(At least it could support consistency_level: Strong/Eventually/Bounded). We could add some similar code as pymilvus does(Maybe later), this is useful to support the `Session` consistency level. It's welcome if you could raise PR for this.
