### ISSUE TITLE
Failed to insert: the num_rows(8) of faceth field is not equal to passed NumRows(1)

### ISSUE THREAD

**Issue by willgamz** [milvus-io/milvus-sdk-cpp#194]
Error inserting BinaryData. Example code:

Returned error:
Failed to insert: the num_rows(8) of faceth field is not equal to passed NumRows(1)

void bin()
{
    auto client = milvus::MilvusClient::Create();

    milvus::ConnectParam connect_param{"localhost", 19530};
    auto status = client->Connect(connect_param);
    CheckStatus("Failed to connect milvus server:", status);
    std::cout << "Connect to milvus server." << std::endl;

    const std::string collection_name = "TEST";
    status = client->DropCollection(collection_name);

    // create a collection
    const std::string field_id_name = "identity";
    const std::string field_face_name = "face";
    const uint32_t dimension = 64;
    milvus::CollectionSchema collection_schema(collection_name);
    collection_schema.AddField({field_id_name, milvus::DataType::INT64, "user id", true, true});
    collection_schema.AddField(milvus::FieldSchema(field_face_name, milvus::DataType::BINARY_VECTOR, "face signature")
                                   .WithDimension(dimension));

    status = client->CreateCollection(collection_schema);
    CheckStatus("Failed to create collection:", status);
    std::cout << "Successfully create collection." << std::endl;

    // create a partition
    std::string partition_name = "Year_2022";
    status = client->CreatePartition(collection_name, partition_name);
    CheckStatus("Failed to create partition:", status);
    std::cout << "Successfully create partition." << std::endl;

    // tell server prepare to load collection
    status = client->LoadCollection(collection_name);
    CheckStatus("Failed to load collection:", status);

     // insert some rows
    std::vector<std::vector<uint8_t>> insert_vectors = {
        {1, 1, 1, 1, 1, 1, 1, 1}};

    std::vector<milvus::FieldDataPtr> fields_data{std::make_shared<milvus::BinaryVecFieldData>(field_face_name, insert_vectors)};
    milvus::DmlResults dml_results;
    status = client->Insert(collection_name, partition_name, fields_data, dml_results);
    CheckStatus("Failed to insert:", status);
    std::cout << "Successfully insert " << dml_results.IdArray().IntIDArray().size() << " rows." << std::endl;
}

The issue is related to: CreateProtoFieldData()

proto::schema::VectorField*
CreateProtoFieldData(const BinaryVecFieldData& field) {
    auto ret = new proto::schema::VectorField{};
    auto& data = field.Data();
    auto dim = data.front().size();
    auto& vectors_data = *(ret->mutable_binary_vector());
    vectors_data.reserve(data.size() * dim);
    for (const auto& item : data) {
        std::copy(item.begin(), item.end(), std::back_inserter(vectors_data));
    }
    ret->set_dim(dim);
    return ret;
}

The dimension of the VectorField shoul be in BITS:
    ret->set_dim(dim * 8); 

This is because at server side the validation is in bits:

https://github.com/milvus-io/milvus/blob/c267ad612d783dde5583e3aadca313be177655b2/internal/util/funcutil/func.go#L283
func getNumRowsOfBinaryVectorField(bDatas []byte, dim int64) (uint64, error) {
	if dim <= 0 {
		return 0, fmt.Errorf("dim(%d) should be greater than 0", dim)
	}
	if dim%8 != 0 {
		return 0, fmt.Errorf("dim(%d) should divide 8", dim)
	}
	l := len(bDatas)
	if (8*int64(l))%dim != 0 {
		return 0, fmt.Errorf("the num(%d) of all bits should divide the dim(%d)", 8*l, dim)
	}
	return uint64((8 * int64(l)) / dim), nil
}

note: uint64((8 * int64(l)) / dim)
Seems to be expecting "dim" in BITS

**Comment by matrixji** [comment]
Currently, we using std::vector<uint8> for BINARY_VECTOR data. Actually, it requires using each uint8 to store 8 bits for BINARY.

And the main branch's implementation is incorrect.
We may introduce some interface changes to handle it:

- Alias BinaryVecFieldData to FieldData<std::vector<std::bitset<8>>, DataType::BINARY_VECTOR>;
- Add BinaryVecFieldData::Add(std::string) for sometimes, user may store binary vectors in bytes string.

After that, I think it will be clearer for how to Add data to BINARY_VECTOR.

**Comment by willgamz** [comment]
hi,
Sorry for the confusion. I should have set 
const uint32_t dimension = 64; to be clear about the error. Yes, vector<uint8_t> will count as 8 bits.But the issue it is not related to that. 

If we run the example code the error will be reproduced.

Fro what I can see: CreateProtoFieldData() for BinaryData is setting the dimensions in bytes, which is apparently correct:
 ret->set_dim(dim);

But the server code is doing the validation in BITS, which trigger the error:
Server code:
getNumRowsOfBinaryVectorField():
    return uint64((8 * int64(l)) / dim), nil

l= the number total bytes of all rows sent.
d= size of one row(actually first row)

That will trigger: the num_rows(8) of faceth field is not equal to passed NumRows(1), because:

NumRows == 1
num_rows of faceth field  = 8  ( 8 * 8 / 8 = 8)

Note if dimensions is in bits:
num_rows of faceth field  = 1  ( 8 * 8 / 8* 8 = 1)  : that is the correct one.

**Comment by matrixji** [comment]
After checking the pymilvus's interface.

How do we add binary vectors when using pymilvus, it just uses the below example code:
```
binary_vectors.append(bytes(np.packbits(raw_vector, axis=-1).tolist()))
```
here raw_vector like: [0, 1, 0, 1, 0, 1, 1, 0], and in such case dimension using 8 (we have 8 bits for each bin vector);

Then how we should design our interface for c++? For my understanding the `std::string` in c++ equals `bytes` in python.

So, we maybe need to change the Add interface to `BinaryVecFieldData::Add(const std::string&);` for it. And we may also have some requirements for input from 0/1 numbers. maybe some helper function(just like `np.packbits`) may be introduced to transform data types like: 
 - std::vector\<uint8_t\> -> std::string, {1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1} -> '\x9595'
 - std::vector\<bool\> -> std::string, {true, false, false, true, false, true, false, true, true, false, false, true, false, true, false, true} -> '\x9595'

So after that change, the c++ code for inserting Binary vectors may be like the below:
```
// ...
const uint32_t dimension = 16;
milvus::CollectionSchema collection_schema(collection_name);
collection_schema.AddField({field_id_name, milvus::DataType::INT64, "user id", true, true});
collection_schema.AddField(milvus::FieldSchema(field_face_name, milvus::DataType::BINARY_VECTOR, "face signature")
                               .WithDimension(dimension));

 // insert one row, 16 bits
std::vector<std::vector<uint8_t>> insert_vector_nums = {{1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1}};
std::vector<std::string> insert_vectors = milvus::Field::CreateBinaryVectors(insert_vector_nums);

std::vector<milvus::FieldDataPtr> fields_data{std::make_shared<milvus::BinaryVecFieldData>(field_face_name, insert_vectors)};
milvus::DmlResults dml_results;
status = client->Insert(collection_name, partition_name, fields_data, dml_results);
```

@willgamz kindly if you could provide some comments for it.

**Comment by willgamz** [comment]
hi

One option is provide the following:

1. keep the existing one which is receiving uint8_t but renaming the template instance from: BinaryVecFieldData to Binary8VecFieldData or something like that. (this one require the dim *8). There is nothing wrong with is and it is more compact to represent uint8 as 8 bits. Just the Template instance need a more clarifying name.

2. add a new type like: BinaryVecFieldData that supports the following inputs.
- std::vector<bool> = {true, false, true, false}    
- std::string ("0101010101010") in bits
- std::string ("090A05") in hex.

I can see that actually to send the data, it is converted to string. If it is possible the implementation 2 should provide "no" reconverting, and ideally "no" copy.

**Comment by matrixji** [comment]
> hi
> 
> One option is to provide the following:
> 
> 1. keep the existing one which is receiving uint8_t (representing 8 bits) but renaming the template instance from: BinaryVecFieldData to Binary8VecFieldData or something like that. (this one require the dim *8). There is nothing wrong with it and it is more compact to represent uint8 as 8 bits. Just the Template instance need a more clarifying name.
> 2. add a new type like: BinaryVecFieldData that supports the following inputs.
> 
> * std::vector = {true, false, true, false}
> * std::string ("0101010101010") in bits
> * std::string ("090A05") in hex.
> 
> I can see that actually to send the data, it is converted to string. If it is possible the implementation 2 should provide "no" reconverting, and ideally "no" copy during sending.

PR #196 is ongoing. And the [test code](https://github.com/milvus-io/milvus-sdk-cpp/blob/cac62e3d185e32e61ea01277290fbd98b630f647/test/st/TestSearchWithBinaryVectors.cpp) shows how to do with binary vectors.

For the `add a new type like: BinaryVecFieldData that supports the following inputs.`, I'd like to raise some new enhancement PRs later.
