### ISSUE TITLE
string data type not supported yet, please use VarChar type instead

### ISSUE THREAD

**Issue by willgamz** [milvus-io/milvus-sdk-cpp#197]
When creating schema as follows:
collection_schema.AddField({field_id_shashex_id, milvus::DataType::STRING, "shash in hex", false, false});

we get the following error: string data type not supported yet, please use VarChar type instead
There is no VarChar type defined on "milvus/types/FieldData.h"

**Comment by matrixji** [comment]
Thanks for your report, the feature for supporting String in the client is planned in #181. If you're interested in it, welcome to contributions

attach #181

**Comment by willgamz** [comment]
hi @matrixji 

When you said "string" you are referring to "VarChar"?
There are to types "String" and "VarChar".
 Or just you are going to support String as VarChar?

**Comment by matrixji** [comment]
> hi @matrixji
> 
> When you said "string" you are referring to "VarChar"? There are to types "String" and "VarChar". Or just you are going to support String as VarChar?

As now only VarChar is supported, I think we need to support VarChar in 2.1,  I guess when #181 was created, the proto definitions still only contain String type.

ref: https://milvus.io/docs/v2.1.x/schema.md

**Comment by matrixji** [comment]
Hi @willgamz 
Could help to check #200 if already support your case. 
You may need some change STRING -> VARCHAR in your code. We now support milvus::DataType::VARCHAR, as the Milvus server supports this.
