### ISSUE TITLE
make通过不了

### ISSUE THREAD

**Issue by yufeixuan** [milvus-io/milvus-sdk-cpp#205]
![image](https://user-images.githubusercontent.com/8575535/204508048-f88f7ba8-13bf-4d19-9739-1d601f11fa46.png)

**Comment by matrixji** [comment]
Which branch you are using? could you provide more details?

**Comment by yufeixuan** [comment]
![image](https://user-images.githubusercontent.com/8575535/204510831-77256c50-2a0f-4b53-88d2-1a33cc1f9a6a.png)
![image](https://user-images.githubusercontent.com/8575535/204510880-d568e4e4-88b6-4caa-92e5-f2a136472f6c.png)
mkdir build
cd build 
cmake ..
make


cmake version 3.22.1

**Comment by matrixji** [comment]
> ![image](https://user-images.githubusercontent.com/8575535/204510831-77256c50-2a0f-4b53-88d2-1a33cc1f9a6a.png) ![image](https://user-images.githubusercontent.com/8575535/204510880-d568e4e4-88b6-4caa-92e5-f2a136472f6c.png) ![image](https://user-images.githubusercontent.com/8575535/204511550-418c717a-4ff0-44f8-bf6b-50fa75e09e56.png)
> 
> git submodule update --init
> 
> mkdir build cd build cmake .. make
> 
> cmake version 3.22.1

Branch 2.0 should not work for current Milvus 2.1/2.2, please update to the master branch.

**Comment by yufeixuan** [comment]
> > ![image](https://user-images.githubusercontent.com/8575535/204510831-77256c50-2a0f-4b53-88d2-1a33cc1f9a6a.png) ![image](https://user-images.githubusercontent.com/8575535/204510880-d568e4e4-88b6-4caa-92e5-f2a136472f6c.png) ![image](https://user-images.githubusercontent.com/8575535/204511550-418c717a-4ff0-44f8-bf6b-50fa75e09e56.png)
> > git submodule update --init
> > mkdir build cd build cmake .. make
> > cmake version 3.22.1
> 
> Branch 2.0 should not work for current Milvus 2.1/2.2, please update to the master branch.

master branch is good, thank you.

**Comment by matrixji** [comment]
> master branch is good, thank you.

Thanks for your feedback.
/close
