### ISSUE TITLE
Failed to search milvus server

### ISSUE THREAD

**Issue by fuguanyu** [milvus-io/milvus-sdk-cpp#217]
![image](https://user-images.githubusercontent.com/104418759/223376201-f0fdf3c8-67f2-4d44-b37a-bedee05ca1cb.png)
timeout = 3000
error: Deadline Exceeded
plz help

**Comment by matrixji** [comment]
@fuguanyu have you resolved your problem?

**Comment by fuguanyu** [comment]
yes!
