### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by Lllll921** [milvus-io/milvus-sdk-cpp#235]
Have this error when compiling:
#error This file was generated by an older version of protoc which is
#error: #error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.

But I only have a protoc version on my computer. Does anyone has this problem?

**Comment by matrixji** [comment]
It seems to conflict with your pre-installed Protobuf, could you provide more information about it, e.g. the operation system name and which protobuf version you have installed? It will help us to reproduce it and than to check how to fix it in out CmakeLists

**Comment by matrixji** [comment]
I raise a PR for always using compiled protoc from the source, you could try it with #236, or update the master source after the PR merged.

**Comment by Lllll921** [comment]
Thanks! My os name is Debian GNU/Linux and my current protoc version is "libprotoc 3.12.4"

**Comment by Lllll921** [comment]
Update: I tried to edit the code in your PR and it works! Thanks a lot!

**Comment by Lllll921** [comment]
One more question, When I try "make install", the library seems doesn't write to usr/local folder. And the install_manifest.txt file is empty. Could you check the reason for this? Thanks!
