### ISSUE TITLE
[Discussion] Naming rule for milvus-sdk-cpp

### ISSUE THREAD

**Issue by matrixji** [milvus-io/milvus-sdk-cpp#25]
Propose to align some naming rules like [Naming](https://google.github.io/styleguide/cppguide.html#Naming), we could discuss here, and summarise to MEP, maybe later become a part of contribution guide. And we could add some basic checks with clang-tidy also.

Currently, I see most of the method using `CamelCase` style, but several not, like
```cpp
// in Status.h
    StatusCode
    code() const {
        return code_;
    }

    std::string
    message() const;
```

```cpp
// in TimeoutSetting.h
    uint32_t
    waiting_timeout() const {
        return waiting_timeout_;
    }

    uint32_t
    waiting_interval() const {
        return waiting_interval_;
    }

    void
    SetInterval(uint32_t waiting_interval) {
        waiting_interval_ = waiting_interval;
    }
```

**Comment by matrixji** [comment]
An initial proposal for naming:
- Namespace should use `lower_case`
- Class should use `CamelCase`
- Enum member should use `UPPER_CASE`
- Function should use `CamelCase`, and the private member Function use `camelBack`

**Comment by yhmo** [comment]
Function name use camel case is ok. In the milvus 1.0 source code, we use low case function name for setter method.
Your proposal make sense, just keep a simple rule is fine.
Then the class member name should be "xxx_xxx_ ".

**Comment by yhmo** [comment]
Naming rule has been accepted, close this issue.
