### ISSUE TITLE
Initial developer guides and improve current install_deps.sh for all active contributors.

### ISSUE THREAD

**Issue by matrixji** [milvus-io/milvus-sdk-cpp#51]
Some guides for helping people to work with build/lint/unit testing locally are needed.
Currently, the install_deps.sh only support Ubuntu 18.04, add more support if possibe.

**Comment by yhmo** [comment]
My OS is Ubuntu 18.04.2 LTS.

**Comment by yhmo** [comment]
It would be better if both support ubuntu and centos.
